### ISSUE TITLE
How to localize control titles?

### ISSUE THREAD

**Issue by agentx-cgn** [runette/ngx-leaflet-fullscreen#10]
Hi,

it seams to me this should do the trick:

```
  public fullscreenOptions = {
    title: {
      'false': 'Vollbildansicht einschalten',
      'true':  'Vollbildansicht ausschalten',
    }
  };

  <leaflet-fullscreen-control
    [map]="map"
    [options]="fullscreenOptions"
  ></leaflet-fullscreen-control>
```
but no success, still 'View Fullscreen', what I'm doing wrong?

**Comment by runette** [comment]
I am not totally sure.

The wrapper just passes the options object to the parent library - so it should work. Let me try and do some diagnostics and see if I can reproduce the error.

**Comment by runette** [comment]
I managed to reproduce the problem and it seems to be, as usual for Amgular, a timing issue.

I will push a new version that should fix the problem in the next couple of days
