### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ojasjain24** [runette/ngx-leaflet-fullscreen#14]
I am using this library for one of the angular application, and getting the following errors:

<img width="755" alt="image" src="https://github.com/runette/ngx-leaflet-fullscreen/assets/59116312/0de7a2ce-f841-4320-83d7-f77083ae2fca">

**Comment by runette** [comment]
This is usually caused by not referenceing the type file as shown in the readme.

This line needs to be at the top of the .ts

```
/// <reference types='@runette/leaflet-fullscreen' />
```
