### ISSUE TITLE
"types/leaflet/index.js"' has no exported member FullscreenOptions error

### ISSUE THREAD

**Issue by DoubyCz** [runette/ngx-leaflet-fullscreen#2]
ERROR in node_modules/@runette/ngx-leaflet-fullscreen/lib/ngx-leaflet-fullscreen.component.d.ts:2:24
- error TS2305: Module '"../../../@types/leaflet/index.js"' has no exported member 'FullscreenOptions'.

node_modules/@types/leaflet/index".Control' has no exported member 'Fullscreen'

**Comment by runette** [comment]
Have you tried putting

```
/// <reference types='@runette/leaflet-fullscreen' />
```

at the top of the component script as discussed in the [article](https://medium.com/runic-software/quick-guide-to-leaflet-controls-in-angular-io-1b35d0807bdb).

Also see the StackBlitz in that article for the reference implementation. That is definitely working.

**Comment by mactep** [comment]
In my case I had to run `npm install @runette/leaflet-fullscreen` to solve it. For some reason it wasn't installed together with the angular package.

**Comment by runette** [comment]
@mactep it is not installed with any angular package and you always have to run the npm install command

**Comment by mactep** [comment]
@runette then we should change the README. It states that this package installs that dependency. Sorry if I'm missing something.

**Comment by runette** [comment]
@mactep 

Aha - got you. I was confused by the reference to 'angular package' which to my mind is a schematic.

The package.json definitely includes the dependency - so I am not sure why this would be so. If you want to add a PR to improve the documentation, I would happily accept it.

**Comment by mactep** [comment]
@runette I should've been clearer about it, sorry. 

I did some testing in a new environment and i didn't need to install the dependency manually, just adding `/// <reference types='@runette/leaflet-fullscreen' />` did it. I don't know what happened in my previous environment tho.

**Comment by runette** [comment]
@mactep  I should have read your comment more clearly. When I get time  - I will add some more about this issue in the README
