### ISSUE TITLE
Module leaflet has no exported member FullscreenOptions

### ISSUE THREAD

**Issue by Chistianxfp** [runette/ngx-leaflet-fullscreen#3]
Hello. Im triying to install with "npm install --legacy-peer-deps @runette/ngx-leaflet-fullscreen" due to dependencies errors but i'm allways getting this error:

**Error: node_modules/@runette/ngx-leaflet-fullscreen/lib/ngx-leaflet-fullscreen.component.d.ts:2:24 - error TS2305: Module '"leaflet"' has no exported member 'FullscreenOptions'.

2 import { Map, Control, FullscreenOptions } from 'leaflet';
                         ~~~~~~~~~~~~~~~~~

Error: node_modules/@runette/ngx-leaflet-fullscreen/lib/ngx-leaflet-fullscreen.component.d.ts:7:22 - error TS2694: Namespace '"........./node_modules/@types/leaflet/index".Control' has no exported member 'Fullscreen'.

7     control: Control.Fullscreen;**

I tried installing "npm install @runette/leaflet-fullscreen" and "npm install --save @types/leaflet.fullscreen" before ngx-leaflet-fullscreen bur error stills appearing.

Angular CLI: 13.1.2
Node: 12.21.0
Package Manager: npm 7.20.1


Thank you for your time.

**Comment by runette** [comment]
Try adding the following line  **as the first line of the component .ts script**

```
/// <reference types='@runette/leaflet-fullscreen' />
```

That should do the tick.

**Comment by codemonkeyneo** [comment]
Had same issue and installing

```
npm install @runette/leaflet-fullscreen
```
Sorts that out :)

**Comment by Chistianxfp** [comment]
> Had same issue and installing
> 
> ```
> npm install @runette/leaflet-fullscreen
> ```
> 
> Sorts that out :)

This solved the problem. Thank you!!
